#ifndef NEARLIGHTER_SHAPE_SHAPE_H
#define NEARLIGHTER_SHAPE_SHAPE_H

#include <nearlighter/base/interval.h>
#include <nearlighter/base/ray.h>
#include <nearlighter/geometry/aabb.h>

class Sampler;

/**
 * Local Surface Interaction
 *
 * Stores the geometry produced by a successful local-space Shape query.
 * - `point` and both normals use the Shape's local coordinates.
 * - `geometric_normal` is the unit outward orientation of the surface.
 * - `shading_normal` may be interpolated, but is unit length and lies in the
 *   same hemisphere as `geometric_normal`.
 * - `t` preserves the input ray parameter; `u` and `v` are Shape-defined
 *   surface coordinates.
 *
 * Shape does not face-forward either normal. Primitive performs orientation,
 * coordinate transformation, and Material binding afterwards.
 */
struct ShapeHit {
    Point3f point;
    Vec3f geometric_normal;
    Vec3f shading_normal;
    float t = 0.0f;
    float u = 0.0f;
    float v = 0.0f;
};

/**
 * Local Geometric Shape
 *
 * Defines intrinsic geometry independently of Material and scene placement.
 * - Intersection returns outward local surface data.
 * - Bounds enclose the geometry in the same local space.
 * - Optional directional sampling describes only the Shape's surface.
 *
 * Implementations are immutable and deterministic except for explicit use of
 * the caller-owned Sampler in `random()`. Primitive supplies Transform and
 * Material responsibilities when the Shape enters the scene.
 */
class Shape {
public:
    virtual ~Shape() = default;

    /**
     * Local Ray Intersection
     *
     * @param ray Ray expressed in the Shape's local coordinate system.
     * @param ray_t Accepted range of ray parameters.
     * @param hit Receives the closest accepted local interaction on success;
     * it remains unchanged on a miss.
     * @return `true` when the ray intersects the surface within `ray_t`.
     */
    virtual bool hit(const Ray& ray, Interval ray_t,
                     ShapeHit& hit) const = 0;

    /**
     * Local Shape Bounds
     *
     * @return Axis-aligned local bounds whose reference remains valid for the
     * Shape's lifetime.
     */
    virtual const AABB& getBoundingBox() const = 0;

    /**
     * Directional Sampling Support
     *
     * @return `true` only when `random()` and `getPDFValue()` implement the
     * same non-default surface sampling distribution.
     */
    virtual bool hasPDF() const { return false; }

    /**
     * Local Direction Density
     *
     * @param origin Sampling origin in local coordinates.
     * @param direction Non-zero query direction; its length has no
     * probabilistic meaning.
     * @return Density generated by this Shape's `random()` strategy with
     * respect to local solid angle in inverse steradians, or zero outside its
     * support.
     */
    virtual float getPDFValue(
        [[maybe_unused]] const Point3f& origin,
        [[maybe_unused]] const Vec3f& direction) const {
        return 0.0f;
    }

    /**
     * Local Direction Sampling
     *
     * @param origin Sampling origin in local coordinates.
     * @param sampler Random stream consumed by the sampling procedure.
     * @return A non-zero direction distributed according to `getPDFValue()`;
     * its length has no probabilistic meaning.
     */
    virtual Vec3f random(
        [[maybe_unused]] const Point3f& origin,
        [[maybe_unused]] Sampler& sampler) const {
        return Vec3f(1.0f, 0.0f, 0.0f);
    }
};

#endif  // NEARLIGHTER_SHAPE_SHAPE_H
